# Generated by Django 6.1.1 on 2026-10-03 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='unidade de medida')),
                ('quantidade_minima', models.PositiveIntegerField(verbose_name='quantidade mínima')),
                ('qtd_atual', models.PositiveIntegerField(default=0, verbose_name='quantidade atual')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Desativado')], default='ativo', max_length=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo', models.CharField(blank=True, choices=[('uso_producao', 'Uso em produção'), ('perda_dano', 'Perda ou dano'), ('ajuste_inventario', 'Ajuste de inventário')], help_text='Só para saída.', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-data', '-pk'],
            },
        ),
    ]
