# Generated by Django 6.1.1 on 2026-10-03 12:49

import contas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='usuário')),
                ('perfil', models.CharField(choices=[('estoque', 'Operacional de Estoque'), ('fretes', 'Operacional de Fretes'), ('gestor', 'Gestor'), ('admin', 'Administrador')], default='estoque', max_length=10)),
                ('ativo', models.BooleanField(default=True, help_text='Exclusão lógica: inativo não entra no sistema.')),
                ('senha_temporaria', models.BooleanField(default=False, help_text='Obriga a troca de senha no próximo acesso.')),
                ('anonimizado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nome', 'username'],
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome_snapshot', models.CharField(max_length=150)),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('exclusao', 'Exclusão')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de ação',
                'verbose_name_plural': 'log de ações',
                'ordering': ['-data_hora', '-pk'],
            },
        ),
    ]
