# Generated by Django 6.1.1 on 2026-10-03 17:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('valor_por_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor por km (R$)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Desativado')], default='ativo', max_length=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('distancia', models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='distância (km)')),
                ('valor_sugerido', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valor cobrado (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=15)),
                ('usuario', models.ForeignKey(help_text='Quem registrou a entrega.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='fretes.entregador')),
            ],
            options={
                'verbose_name_plural': 'entregas',
                'ordering': ['-data', '-pk'],
            },
        ),
    ]
